# -*- coding: utf-8 -*-
"""Tracking User Engagement with SQL, Excel, and Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rT21npanbRzvYGVKHOmeFiDUL0avrf6n

**# Step 1 & 2: Import Libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style='whitegrid')

"""**# Step 3: Load the Data**"""

data_free_2021 = pd.read_csv('minutes_watched_2021_paid_0.csv')
data_free_2022 = pd.read_csv('minutes_watched_2022_paid_0.csv')
data_paid_2021 = pd.read_csv('minutes_watched_2021_paid_1.csv')
data_paid_2022 = pd.read_csv('minutes_watched_2022_paid_1.csv')

"""**# Step 4: Explore Data**"""

print(data_free_2021.head())
print(data_paid_2022.head())

"""**# Step 5: Plot Distributions (Before Outlier Removal)**"""

fig, axes = plt.subplots(2, 2, figsize=(15,10))
sns.kdeplot(data_free_2021['minutes_watched'], ax=axes[0,0]).set(title='Free Q2 2021')
sns.kdeplot(data_free_2022['minutes_watched'], ax=axes[0,1]).set(title='Free Q2 2022')
sns.kdeplot(data_paid_2021['minutes_watched'], ax=axes[1,0]).set(title='Paid Q2 2021')
sns.kdeplot(data_paid_2022['minutes_watched'], ax=axes[1,1]).set(title='Paid Q2 2022')
fig.tight_layout(pad=3.0)
plt.show()

"""**# Step 6: Find 99th Percentiles**"""

def remove_outliers(df):
    q99 = df['minutes_watched'].quantile(0.99)
    return df[df['minutes_watched'] < q99]

data_free_2021_clean = remove_outliers(data_free_2021)
data_free_2022_clean = remove_outliers(data_free_2022)
data_paid_2021_clean = remove_outliers(data_paid_2021)
data_paid_2022_clean = remove_outliers(data_paid_2022)

"""**# Step 7: Remove Outliers**"""

fig, axes = plt.subplots(2, 2, figsize=(15,10))
sns.kdeplot(data_free_2021_clean['minutes_watched'], ax=axes[0,0]).set(title='Free Q2 2021 (No Outliers)')
sns.kdeplot(data_free_2022_clean['minutes_watched'], ax=axes[0,1]).set(title='Free Q2 2022 (No Outliers)')
sns.kdeplot(data_paid_2021_clean['minutes_watched'], ax=axes[1,0]).set(title='Paid Q2 2021 (No Outliers)')
sns.kdeplot(data_paid_2022_clean['minutes_watched'], ax=axes[1,1]).set(title='Paid Q2 2022 (No Outliers)')
fig.tight_layout(pad=3.0)
plt.show()

"""**# Step 8: Save Cleaned Data**"""

data_free_2021_clean.to_csv('minutes_watched_2021_paid_0_no_outliers.csv', index=False)
data_free_2022_clean.to_csv('minutes_watched_2022_paid_0_no_outliers.csv', index=False)
data_paid_2021_clean.to_csv('minutes_watched_2021_paid_1_no_outliers.csv', index=False)
data_paid_2022_clean.to_csv('minutes_watched_2022_paid_1_no_outliers.csv', index=False)

print("Task 4 completed: Outliers removed and cleaned CSV files saved.")